const SHEET_CSV='https://docs.google.com/spreadsheets/d/1YCfoVNaRcGLA_n6Om9eXLoLmdvVQbh-T6Javx306ZTM/gviz/tq?tqx=out:csv';
const APPROVED=['approved','অনুমোদিত','প্রকাশিত','published'];
function parseCSV(t){const rows=[];let row=[],cell='',q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function norm(s){return String(s||'').toLowerCase().replace(/[\s_\-]/g,'')}
function col(h,terms){const nh=h.map(norm);for(const t of terms){const nt=norm(t);const exact=nh.findIndex(x=>x===nt);if(exact>=0)return exact}for(const t of terms){const nt=norm(t);const partial=nh.findIndex(x=>x.includes(nt));if(partial>=0)return partial}return -1}
function escapeHTML(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function imageInfo(v){const s=String(v||'').trim();if(!s)return null;const m=s.match(/(?:file\/d\/|id=|[?&]id=)([A-Za-z0-9_-]{15,})/);if(!m)return {src:s,link:s};const id=m[1];return {src:`https://drive.google.com/thumbnail?id=${id}&sz=w1600`,alt:`https://lh3.googleusercontent.com/d/${id}=w1600`,fallback:`https://drive.google.com/uc?export=view&id=${id}`,link:`https://drive.google.com/file/d/${id}/view`}}
async function getPosts(){const r=await fetch(SHEET_CSV+'&v='+Date.now());const rows=parseCSV(await r.text());if(rows.length<2)return[];const h=rows[0];const ix={title:col(h,['লেখারশিরোনাম','title']),author:col(h,['লেখকেরনাম','author']),cat:col(h,['লেখারবিভাগ','বিভাগ','category']),body:col(h,['আপনারলেখাএখানেলিখুন','content','লেখা']),img:col(h,['ছবিবাফাইলথাকলেদিন','ছবি','image','file']),status:col(h,['status'])};return rows.slice(1).map((r,n)=>({id:n,title:r[ix.title]||'শিরোনামহীন লেখা',author:r[ix.author]||'পরিবারের একজন সদস্য',cat:r[ix.cat]||'অন্যান্য',body:r[ix.body]||'',image:imageInfo(r[ix.img]),status:norm(r[ix.status])})).filter(p=>APPROVED.includes(p.status)&&p.body.trim())}
function imgTag(im,title){if(!im)return'';return `<figure class="post-image"><img src="${escapeHTML(im.src)}" data-alt="${escapeHTML(im.alt||'')}" data-fallback="${escapeHTML(im.fallback||'')}" alt="${escapeHTML(title)}" onerror="if(this.dataset.alt){this.src=this.dataset.alt;this.dataset.alt='';}else if(this.dataset.fallback){this.src=this.dataset.fallback;this.dataset.fallback='';}else{this.parentElement.classList.add('image-failed')}"/><figcaption><a href="${escapeHTML(im.link||im.src)}" target="_blank" rel="noopener">ছবিটি আলাদা করে দেখুন ↗</a></figcaption></figure>`}
function card(p,i){return `<article class="post"><div class="post-top"><span class="meta">${escapeHTML(p.cat)}</span><span class="date">পরিবারের পাতা</span></div><h3><a href="article.html?i=${i}">${escapeHTML(p.title)}</a></h3><small>লিখেছেন — ${escapeHTML(p.author)}</small>${imgTag(p.image,p.title)}<p>${escapeHTML(p.body)}</p><a class="read-more" href="article.html?i=${i}">পুরো লেখা পড়ুন →</a></article>`}
function renderHome(posts){const box=document.querySelector('#sheet-posts');if(!box)return;if(!posts.length){box.innerHTML='<div class="empty">এখনও কোনো লেখা প্রকাশিত হয়নি।</div>';return}const cats=[...new Set(posts.map(p=>p.cat))];box.innerHTML=cats.map(cat=>`<section class="category-block"><div class="category-heading"><span class="label">বিভাগ</span><h3>${escapeHTML(cat)}</h3><a href="article.html?category=${encodeURIComponent(cat)}">সব লেখা →</a></div><div class="posts">${posts.filter(p=>p.cat===cat).slice(0,3).map(p=>card(p,posts.indexOf(p))).join('')}</div></section>`).join('')}
function renderArticle(posts){const root=document.querySelector('#article-content');if(!root)return;const params=new URLSearchParams(location.search);const cat=params.get('category');if(cat){const filtered=posts.filter(p=>p.cat===cat);root.innerHTML=`<a class="back" href="index.html#posts">← প্রচ্ছদে ফিরুন</a><div class="section-title"><span class="label">বিভাগ</span><h1>${escapeHTML(cat)}</h1></div><div class="posts">${filtered.map(p=>card(p,posts.indexOf(p))).join('')||'<div class="empty">এই বিভাগে এখনও কোনো লেখা নেই।</div>'}</div>`;return}const p=posts[Number(params.get('i'))];if(!p){root.innerHTML='<div class="empty">লেখাটি পাওয়া যায়নি।</div>';return}root.innerHTML=`<a class="back" href="index.html#posts">← সব লেখায় ফিরুন</a><article class="article-content"><div class="label">${escapeHTML(p.cat)}</div><h1>${escapeHTML(p.title)}</h1><small>লিখেছেন — ${escapeHTML(p.author)}</small>${imgTag(p.image,p.title)}<div class="body">${escapeHTML(p.body)}</div></article>`}
(async()=>{try{const posts=await getPosts();renderHome(posts);renderArticle(posts)}catch(e){document.querySelectorAll('#sheet-posts,#article-content').forEach(x=>x.innerHTML='<div class="empty">এই মুহূর্তে লেখা লোড করা যাচ্ছে না। কিছুক্ষণ পরে আবার চেষ্টা করুন।</div>')}})();
